TrialOfTheGreyMatter: main.c
	gcc camera.c camera.h characters.c characters.h collision.c collision.h menu.c menu_func.c menuheader.h header.h main.c settings.c settings_func.c settingsheader.h objects.c objects.h level1.c level1.h level1_func.c ingamemenu.c ingamemenu.h ingamemenu_func.c loadgame.c loadgame_func.c loadgame.h health.c health.h minimap.c minimap.h -o game -lSDL -lSDL_image -lSDL_mixer
clean:
	rm -fr game
execute:
	./game
